/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as VendedorRouteImport } from './routes/vendedor'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAdminsRouteImport } from './routes/admin.admins'
import { Route as AdminComissoesRouteImport } from './routes/admin.comissoes'
import { Route as AdminConfigRouteImport } from './routes/admin.config'
import { Route as AdminCuponsRouteImport } from './routes/admin.cupons'
import { Route as AdminHistoricoRouteImport } from './routes/admin.historico'
import { Route as AdminPdvRouteImport } from './routes/admin.pdv'
import { Route as AdminPixRouteImport } from './routes/admin.pix'
import { Route as AdminPrecosRouteImport } from './routes/admin.precos'
import { Route as AdminVendedoresRouteImport } from './routes/admin.vendedores'
import { Route as PedidoIdRouteImport } from './routes/pedido.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const VendedorRoute = VendedorRouteImport.update({
  id: '/vendedor',
  path: '/vendedor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComissoesRoute = AdminComissoesRouteImport.update({
  id: '/comissoes',
  path: '/comissoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCuponsRoute = AdminCuponsRouteImport.update({
  id: '/cupons',
  path: '/cupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHistoricoRoute = AdminHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPdvRoute = AdminPdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPixRoute = AdminPixRouteImport.update({
  id: '/pix',
  path: '/pix',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPrecosRoute = AdminPrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVendedoresRoute = AdminVendedoresRouteImport.update({
  id: '/vendedores',
  path: '/vendedores',
  getParentRoute: () => AdminRoute,
} as any)
const PedidoIdRoute = PedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/vendedor': typeof VendedorRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/comissoes': typeof AdminComissoesRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/historico': typeof AdminHistoricoRoute
  '/admin/pdv': typeof AdminPdvRoute
  '/admin/pix': typeof AdminPixRoute
  '/admin/precos': typeof AdminPrecosRoute
  '/admin/vendedores': typeof AdminVendedoresRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/vendedor': typeof VendedorRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/comissoes': typeof AdminComissoesRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/historico': typeof AdminHistoricoRoute
  '/admin/pdv': typeof AdminPdvRoute
  '/admin/pix': typeof AdminPixRoute
  '/admin/precos': typeof AdminPrecosRoute
  '/admin/vendedores': typeof AdminVendedoresRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/vendedor': typeof VendedorRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/comissoes': typeof AdminComissoesRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/historico': typeof AdminHistoricoRoute
  '/admin/pdv': typeof AdminPdvRoute
  '/admin/pix': typeof AdminPixRoute
  '/admin/precos': typeof AdminPrecosRoute
  '/admin/vendedores': typeof AdminVendedoresRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/vendedor'
    | '/admin/admins'
    | '/admin/comissoes'
    | '/admin/config'
    | '/admin/cupons'
    | '/admin/historico'
    | '/admin/pdv'
    | '/admin/pix'
    | '/admin/precos'
    | '/admin/vendedores'
    | '/pedido/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/vendedor'
    | '/admin/admins'
    | '/admin/comissoes'
    | '/admin/config'
    | '/admin/cupons'
    | '/admin/historico'
    | '/admin/pdv'
    | '/admin/pix'
    | '/admin/precos'
    | '/admin/vendedores'
    | '/pedido/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/vendedor'
    | '/admin/admins'
    | '/admin/comissoes'
    | '/admin/config'
    | '/admin/cupons'
    | '/admin/historico'
    | '/admin/pdv'
    | '/admin/pix'
    | '/admin/precos'
    | '/admin/vendedores'
    | '/pedido/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  VendedorRoute: typeof VendedorRoute
  PedidoIdRoute: typeof PedidoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendedor': {
      id: '/vendedor'
      path: '/vendedor'
      fullPath: '/vendedor'
      preLoaderRoute: typeof VendedorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comissoes': {
      id: '/admin/comissoes'
      path: '/comissoes'
      fullPath: '/admin/comissoes'
      preLoaderRoute: typeof AdminComissoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/config': {
      id: '/admin/config'
      path: '/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cupons': {
      id: '/admin/cupons'
      path: '/cupons'
      fullPath: '/admin/cupons'
      preLoaderRoute: typeof AdminCuponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/historico': {
      id: '/admin/historico'
      path: '/historico'
      fullPath: '/admin/historico'
      preLoaderRoute: typeof AdminHistoricoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pdv': {
      id: '/admin/pdv'
      path: '/pdv'
      fullPath: '/admin/pdv'
      preLoaderRoute: typeof AdminPdvRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pix': {
      id: '/admin/pix'
      path: '/pix'
      fullPath: '/admin/pix'
      preLoaderRoute: typeof AdminPixRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/precos': {
      id: '/admin/precos'
      path: '/precos'
      fullPath: '/admin/precos'
      preLoaderRoute: typeof AdminPrecosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vendedores': {
      id: '/admin/vendedores'
      path: '/vendedores'
      fullPath: '/admin/vendedores'
      preLoaderRoute: typeof AdminVendedoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/pedido/$id': {
      id: '/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof PedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminComissoesRoute: typeof AdminComissoesRoute
  AdminConfigRoute: typeof AdminConfigRoute
  AdminCuponsRoute: typeof AdminCuponsRoute
  AdminHistoricoRoute: typeof AdminHistoricoRoute
  AdminPdvRoute: typeof AdminPdvRoute
  AdminPixRoute: typeof AdminPixRoute
  AdminPrecosRoute: typeof AdminPrecosRoute
  AdminVendedoresRoute: typeof AdminVendedoresRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminsRoute: AdminAdminsRoute,
  AdminComissoesRoute: AdminComissoesRoute,
  AdminConfigRoute: AdminConfigRoute,
  AdminCuponsRoute: AdminCuponsRoute,
  AdminHistoricoRoute: AdminHistoricoRoute,
  AdminPdvRoute: AdminPdvRoute,
  AdminPixRoute: AdminPixRoute,
  AdminPrecosRoute: AdminPrecosRoute,
  AdminVendedoresRoute: AdminVendedoresRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  VendedorRoute: VendedorRoute,
  PedidoIdRoute: PedidoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
